# Generated by Django 5.0.2 on 2025-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0002_alter_auditiondata_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditiondata',
            name='domain',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
