# Generated by Django 5.0.2 on 2025-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0005_auditiondata_department_auditiondata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditiondata',
            name='questions_answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
