# Generated by Django 5.0.2 on 2025-01-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0006_auditiondata_questions_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditiondata',
            name='questions_answers2',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
