# Generated by Django 5.0.2 on 2025-01-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0007_auditiondata_questions_answers2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditiondata',
            name='questions_answers2',
        ),
    ]
