# Generated by Django 5.0.2 on 2025-01-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0008_remove_auditiondata_questions_answers2'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditiondata',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
