# Generated by Django 5.0.2 on 2025-01-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0010_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditiondata',
            name='year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
