# Generated by Django 5.2.7 on 2026-02-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0011_auditiondata_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditiondata',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
