# Generated by Django 5.2.7 on 2026-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0012_alter_auditiondata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditiondata',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
