# Generated by Django 5.2.7 on 2026-03-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditionForm', '0014_alter_auditiondata_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AlterField(
            model_name='auditiondata',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
